function get_graph_metrics(A)

disp('Number of Edges')
Edges = get_number_of_edges(A)
disp('Number of Wedges')
Wedges = get_number_of_wedges(A)
disp('Number of Triangles')
Triangles = get_number_of_triangles(A)
disp('Number of Arrows')
Arrows = get_number_of_arrows(A)
disp('Number of Buckets')
Buckets = get_number_of_buckets(A)
disp('Number of Nooses')
Nooses = get_number_of_nooses(A)
disp('Number of Quadrangles')
Quadrangles = get_number_of_quadrangles(A)
disp('Number of Smart Pentagons')
Pentagons = get_number_of_pentagons(A)
end
